#!/usr/bin/env php
<?php

/**
 *  Register the auto loader
 */
require __DIR__.'/../vendor/autoload.php';

/**
 * Defines needed constants
 */
define('FACILIOR_START', date('Ymd-Hsi'));
define('FACILIOR_BIN', __DIR__);
define('FACILIOR_ROOT', realpath(getcwd() . '/.facilior'));
define('FACILIOR_LOG', realpath(getcwd() . '/.facilior/logs'));

logger("test");


/**
 * Instanciate a new Kernel object
 */
$kernel = new \Nolotz\Facilior\Console\Kernel();

$status = $kernel->handle(
    new \Symfony\Component\Console\Input\ArgvInput,
    new \Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);
